# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files\Cmake\cmake-3.24.1-windows-x86_64\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files\Cmake\cmake-3.24.1-windows-x86_64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Users\Admin\Desktop\PROJECTS\Simple

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Users\Admin\Desktop\PROJECTS\Simple

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"D:\Program Files\Cmake\cmake-3.24.1-windows-x86_64\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\Program Files\Cmake\cmake-3.24.1-windows-x86_64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Users\Admin\Desktop\PROJECTS\Simple\CMakeFiles D:\Users\Admin\Desktop\PROJECTS\Simple\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Users\Admin\Desktop\PROJECTS\Simple\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named program

# Build rule for target.
program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 program
.PHONY : program

# fast build rule for target.
program/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/build
.PHONY : program/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\run.dir\build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\clean-all.dir\build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

Simple/Src/Shapes/Scene.obj: Simple/Src/Shapes/Scene.cpp.obj
.PHONY : Simple/Src/Shapes/Scene.obj

# target to build an object file
Simple/Src/Shapes/Scene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Simple/Src/Shapes/Scene.cpp.obj
.PHONY : Simple/Src/Shapes/Scene.cpp.obj

Simple/Src/Shapes/Scene.i: Simple/Src/Shapes/Scene.cpp.i
.PHONY : Simple/Src/Shapes/Scene.i

# target to preprocess a source file
Simple/Src/Shapes/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Simple/Src/Shapes/Scene.cpp.i
.PHONY : Simple/Src/Shapes/Scene.cpp.i

Simple/Src/Shapes/Scene.s: Simple/Src/Shapes/Scene.cpp.s
.PHONY : Simple/Src/Shapes/Scene.s

# target to generate assembly for a file
Simple/Src/Shapes/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Simple/Src/Shapes/Scene.cpp.s
.PHONY : Simple/Src/Shapes/Scene.cpp.s

Simple/Src/Window.obj: Simple/Src/Window.cpp.obj
.PHONY : Simple/Src/Window.obj

# target to build an object file
Simple/Src/Window.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Simple/Src/Window.cpp.obj
.PHONY : Simple/Src/Window.cpp.obj

Simple/Src/Window.i: Simple/Src/Window.cpp.i
.PHONY : Simple/Src/Window.i

# target to preprocess a source file
Simple/Src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Simple/Src/Window.cpp.i
.PHONY : Simple/Src/Window.cpp.i

Simple/Src/Window.s: Simple/Src/Window.cpp.s
.PHONY : Simple/Src/Window.s

# target to generate assembly for a file
Simple/Src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Simple/Src/Window.cpp.s
.PHONY : Simple/Src/Window.cpp.s

Src/main.obj: Src/main.cpp.obj
.PHONY : Src/main.obj

# target to build an object file
Src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Src/main.cpp.obj
.PHONY : Src/main.cpp.obj

Src/main.i: Src/main.cpp.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make CMakeFiles/program.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... clean-all
	@echo ... run
	@echo ... program
	@echo ... Simple/Src/Shapes/Scene.obj
	@echo ... Simple/Src/Shapes/Scene.i
	@echo ... Simple/Src/Shapes/Scene.s
	@echo ... Simple/Src/Window.obj
	@echo ... Simple/Src/Window.i
	@echo ... Simple/Src/Window.s
	@echo ... Src/main.obj
	@echo ... Src/main.i
	@echo ... Src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

